apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-apps
  namespace: argocd
spec:
  project: hello-world
  source:
    repoURL: https://github.com/nguyenthengocdev/dev-kubernetes.git # Update this with your repo URL
    targetRevision: HEAD
    path: envs/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
