apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-world-dev
  namespace: argocd
spec:
  project: hello-world
  source:
    repoURL: https://github.com/nguyenthengocdev/dev-kubernetes.git
    targetRevision: HEAD
    path: envs/dev/hello-world
  destination:
    server: https://kubernetes.default.svc
    namespace: hello-world-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
