apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/nguyenthengocdev/dev-kubernetes.git
    targetRevision: main
    path: apps/hello-world
    helm:
      valueFiles:
        - values.yaml
        - prod-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: test-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
